name: Build y deploy de front

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout 
                uses: actions/checkout@v3

            -   name: Configurar Node.js
                uses: actions/setup-node@v3
                with:
                    node-version: '18'
            
            -   name: Instalar dependencias
                run: npm install

            -   name: Ejecutar lin
                run: npm run lint
                continue-on-error: true

            -   name: Hacer pruebas
                run: npm test
                continue-on-error: true
            
            -   name: Build
                run: npm run build

            -   name: Verificar output
                run: ls -ls dist

            -   name: Deploy
                uses: peaceiris/actions-gh-pages@v3
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./dist
