name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
      
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18'
      
        - name: Install dependencies
          run: npm install  # Ensure all dependencies (including ESLint) are installed
      
        - name: Run linter
          run: npx eslint .


  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Verify Vite installation
        run: npx vite --version
      - name: Build application
        run: npm run build
